# Generated by Django 5.2.5 on 2026-04-03 08:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_imagenproducto_marca_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de inicio del descuento')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de fin del descuento (vacío = sin límite)', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Activar o desactivar descuento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del descuento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.OneToOneField(help_text='Categoría a la que aplica el descuento', on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='shop.categoria')),
            ],
            options={
                'verbose_name': 'Descuento por Categoría',
                'verbose_name_plural': 'Descuentos por Categoría',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de inicio del descuento')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de fin del descuento (vacío = sin límite)', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Activar o desactivar descuento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del descuento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('marca', models.OneToOneField(help_text='Marca a la que aplica el descuento', on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='shop.marca')),
            ],
            options={
                'verbose_name': 'Descuento por Marca',
                'verbose_name_plural': 'Descuentos por Marca',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de inicio del descuento')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de fin del descuento (vacío = sin límite)', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Activar o desactivar descuento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del descuento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(help_text='Producto al que aplica el descuento', on_delete=django.db.models.deletion.CASCADE, related_name='descuento', to='shop.producto')),
            ],
            options={
                'verbose_name': 'Descuento por Producto',
                'verbose_name_plural': 'Descuentos por Producto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
