# Generated by Django 5.2.5 on 2026-01-14 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='URL de la imagen del producto', upload_to='productos/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (0 = imagen principal)')),
                ('es_principal', models.BooleanField(db_index=True, default=False, help_text='Imagen que se muestra en listados')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para SEO y accesibilidad', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Imagen visible en galería')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre de la marca (ej: Dell, Samsung, Logitech)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la marca')),
                ('logo', models.ImageField(blank=True, help_text='URL del logo de la marca', null=True, upload_to='marcas/')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Marca visible en filtros')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en filtros (menor = primero)')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Producto visible en tienda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción detallada con características técnicas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(db_index=True, default=False, help_text='Mostrar en página principal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict, help_text='Especificaciones técnicas en formato JSON'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='nuevo',
            field=models.BooleanField(default=False, help_text="Etiquetar como 'Nuevo'"),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único de inventario', max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='shop.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre completo del producto', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['activo', 'orden'], name='shop_catego_activo_a790a2_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['slug', 'activo'], name='shop_catego_slug_84bc7d_idx'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(help_text='Producto al que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='shop.producto'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['activo', 'orden'], name='shop_marca_activo_283ef5_idx'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='Fabricante del producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='shop.marca'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug', 'activo'], name='shop_produc_slug_e055f2_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='shop_produc_categor_3c14a7_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['marca', 'activo'], name='shop_produc_marca_i_0d1541_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'destacado'], name='shop_produc_activo_5ee01c_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='precio_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto', 'orden'], name='shop_imagen_product_543876_idx'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto', 'es_principal'], name='shop_imagen_product_137c25_idx'),
        ),
    ]
