# Generated by Django 5.2.5 on 2026-04-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado al momento de agregar', max_digits=5),
        ),
    ]
